In [2]:
from connec_functions import execute_to_df, generate_sparql
import pandas as pd

(Because of different analysis method, using the linked data, results can differ a bit.  
Linked data makes it faster/easier to analyse a larger amount of data)

### Publications in the LifeWatch special collections:

In [14]:
spcol_pubs = execute_to_df("0_spcol_pubs.sparql")
spcol_pubs

,collection,title,publication
0,http://dev.marineinfo.org/id/collection/919,EurOBIS ackn,http://dev.marineinfo.org/id/publication/294591
1,http://dev.marineinfo.org/id/collection/919,EurOBIS ackn,http://dev.marineinfo.org/id/publication/254492
2,http://dev.marineinfo.org/id/collection/919,EurOBIS ackn,http://dev.marineinfo.org/id/publication/254622
3,http://dev.marineinfo.org/id/collection/919,EurOBIS ackn,http://dev.marineinfo.org/id/publication/290470
4,http://dev.marineinfo.org/id/collection/919,EurOBIS ackn,http://dev.marineinfo.org/id/publication/254506
...,...,...,...
47186,http://dev.marineinfo.org/id/collection/947,WoRMS ackn - direct reference,http://dev.marineinfo.org/id/publication/368941
47187,http://dev.marineinfo.org/id/collection/947,WoRMS ackn - direct reference,http://dev.marineinfo.org/id/publication/368936
47188,http://dev.marineinfo.org/id/collection/947,WoRMS ackn - direct reference,http://dev.marineinfo.org/id/publication/368942
47189,http://dev.marineinfo.org/id/collection/947,WoRMS ackn - direct reference,http://dev.marineinfo.org/id/publication/368940
47190,http://dev.marineinfo.org/id/collection/947,WoRMS ackn - direct reference,http://dev.marineinfo.org/id/publication/368934

In [15]:
#LifeWatch special collections with number of publications
lw_spcols = spcol_pubs.groupby('collection').nunique()
lw_spcols

                                             title  publication
collection
http://dev.marineinfo.org/id/collection/793      2          765
http://dev.marineinfo.org/id/collection/896      1          318
http://dev.marineinfo.org/id/collection/897      1           13
http://dev.marineinfo.org/id/collection/915      2         8186
http://dev.marineinfo.org/id/collection/919      2          359
http://dev.marineinfo.org/id/collection/923      2          942
http://dev.marineinfo.org/id/collection/941      1         9188
http://dev.marineinfo.org/id/collection/942      2           87
http://dev.marineinfo.org/id/collection/944      2           27
http://dev.marineinfo.org/id/collection/945      2          262
http://dev.marineinfo.org/id/collection/947      2         8188
http://dev.marineinfo.org/id/collection/986      1           23
http://dev.marineinfo.org/id/collection/987      1           17

In [16]:
test = spcol_pubs[ spcol_pubs['collection'] == 'http://dev.marineinfo.org/id/collection/915']
test.groupby('publication').nunique()

                                                 collection  title
publication
http://dev.marineinfo.org/id/publication/100077           1      2
http://dev.marineinfo.org/id/publication/100293           1      2
http://dev.marineinfo.org/id/publication/100297           1      2
http://dev.marineinfo.org/id/publication/100354           1      2
http://dev.marineinfo.org/id/publication/100404           1      2
...                                                     ...    ...
http://dev.marineinfo.org/id/publication/99721            1      2
http://dev.marineinfo.org/id/publication/99798            1      2
http://dev.marineinfo.org/id/publication/99962            1      2
http://dev.marineinfo.org/id/publication/99971            1      2
http://dev.marineinfo.org/id/publication/99972            1      2

[8186 rows x 2 columns]

In [5]:
# Number of LifeWatch publications - many occur in multiple collections 
lw_pubs = spcol_pubs.groupby('publication').nunique()

print(f'There are {lw_pubs.shape[0]} publications in the LW special collections.')
lw_pubs

There are 3811 publications in the LW special collections.

                                                 collection  title
publication
http://dev.marineinfo.org/id/publication/100295           3      5
http://dev.marineinfo.org/id/publication/100297           5      9
http://dev.marineinfo.org/id/publication/100343           3      5
http://dev.marineinfo.org/id/publication/100354           3      5
http://dev.marineinfo.org/id/publication/100534           3      5
...                                                     ...    ...
http://dev.marineinfo.org/id/publication/97370            2      3
http://dev.marineinfo.org/id/publication/97418            5      9
http://dev.marineinfo.org/id/publication/98075            3      5
http://dev.marineinfo.org/id/publication/99962            3      5
http://dev.marineinfo.org/id/publication/99971            3      5

[3811 rows x 2 columns]